# @package _global_

# Model
model:
  _target_: models.EfBase.base.EfficientBase
  image_encoder:
    _target_: models.EfBase.dino.DINOv3_Adapter
    d_model: 256
    backbone:
      _target_: models.EfBase.dinov3.hub.backbones.dinov3_vitl16
      interaction_indexes: [ 5, 11, 18, 23 ]
  text_encoder:
    _target_: transformers.RobertaModel.from_pretrained
    pretrained_model_name_or_path: 'pretrain/roberta'
  audio_encoder:
    _target_: models.torchvggish.vggish.VGGish2
    pretrained_vggish_model_path: '/18018998051/AVSegFormer/pretrained/vggish-10086976.pth'
    pretrained_pca_params_path: '/18018998051/AVSegFormer/pretrained/vggish_pca_params-970ea276.pth'
    freeze_audio_extractor: True
    preprocess_audio_to_log_mel: False
    postprocess_log_mel_with_pca: False
  text_tokenizer:
    _target_: transformers.RobertaTokenizerFast.from_pretrained
    pretrained_model_name_or_path: 'pretrain/roberta'
  interactor: # 特征交互层
    _target_: models.EfBase.interactor.AddInteractor
    d_model: 256
    num_heads: 8
    num_layers: 6
  decoder:
    _target_: models.EfBase.head.AVSegHead
    in_channels: [256, 256, 256, 256]
    num_classes: 1
    query_num: 300
    use_learnable_queries: True
    query_generator:
      _target_: models.EfBase.utils.query_generator.AttentionGenerator
      num_layers: 6
      query_num: 300
    positional_encoding:
      _target_: models.EfBase.utils.positional_encoding.SinePositionalEncoding
      num_feats: 128
    transformer:
      _target_: models.EfBase.utils.transformer.AVSTransformer
      encoder:
        _target_: models.EfBase.utils.transformer.AVSTransformerEncoder
        num_layers: 6
        layer:
          _target_: models.EfBase.utils.transformer.AVSTransformerEncoderLayer
          dim: 256
          ffn_dim: 2048
          dropout: 0.1
      decoder:
        _target_: models.EfBase.utils.transformer.AVSTransformerDecoder
        num_layers: 6
        layer:
          _target_: models.EfBase.utils.transformer.AVSTransformerDecoderLayer
          dim: 256
          ffn_dim: 2048
          dropout: 0.1
  multi_layers: True
  full_text: True
  image_size: 384
  audio_feature_dim: 128
  text_feature_dim: 768